### ISSUE TITLE
Error when compiling from source

### ISSUE THREAD

**Issue by szhan** [BenoitMorel/AleRax#1]
Thank you for developing this tool!

I'm trying to compile the source code on my Mac. I'm encountering errors when it gets to `AleEvaluator.cpp` and `AleOptimizer.cpp`. Below are some of the error messages I got.

```
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/algorithm:3877:20: error: no matching function for call to '__sort3'
    unsigned __r = _VSTD::__sort3<_Compare>(__x1, __x2, __x3, __c);
                   ^~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/__config:856:15: note: expanded from macro '_VSTD'
#define _VSTD std::_LIBCPP_ABI_NAMESPACE
              ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/algorithm:4098:20: note: in instantiation of function template specialization 'std::__sort4<std::__less<ScoredString> &, ScoredString *>' requested here
            _VSTD::__sort4<_Compare>(__first, __first+1, __first+2, --__last, __comp);
```

I'm using `gcc` version 13.0.0 and `cmake` version 3.27.7. Any pointers would be much appreciated. Thanks in advance.

**Comment by BenoitMorel** [comment]
Hello!
Thanks a lot for your report! I stupidly forgot to check compilation on
macos. It should be fixed now. You need to update the repository with "git
pull" and compile again. Let me know if it works and do not hesitate to
come back to me if you encounter any issues.
Benoit

Le lun. 9 oct. 2023 à 15:14, Shing Hei Zhan ***@***.***> a
écrit :

**Comment by szhan** [comment]
It compiles fine now. Thank you for fixing this!
