### ISSUE TITLE
inconsistency between help and arguments

### ISSUE THREAD

**Issue by DPANN** [BenoitMorel/AleRax#2]
Hi Benoit,

Thanks for developing this tool. I tired to use --species-categories and --fraction-missing option in my analysis, but found that these two options are shown as "--speciies-categories" and " --fraction-missing-file" in the help message. See below.
 
Arguments:
https://github.com/BenoitMorel/AleRax/blob/1d7ea777575f4954b43541e21e3721247389638d/src/ale/AleArguments.cpp#L102C1-L104C48

Help:
https://github.com/BenoitMorel/AleRax/blob/1d7ea777575f4954b43541e21e3721247389638d/src/ale/AleArguments.cpp#L262C1-L265C71

**Comment by BenoitMorel** [comment]
Hi,
Thank you very much for spotting this. It should be fixed now (the correct
arguments are: --species-categories and --fraction-missing-file)
Best,
Benoit

Le ven. 13 oct. 2023 à 11:45, Wen-Cong Huang ***@***.***> a
écrit :
