### ISSUE TITLE
Not an issue, a general discussion.

### ISSUE THREAD

**Issue by karthickbrlab** [BenoitMorel/AleRax#7]
HI,
I have generated individual gene trees for 10 genes among 12 species using ParGenes.
Now how can i use all these tree to infer single species tree using AleRax, which depicts the divergence among the species.

which parameter i should invoke?

Thank you.

**Comment by BenoitMorel** [comment]
Hello,
If you have generated one tree per gene family, you don't necessarily need
to use AleRax (which takes as input distributions of gene trees instead of
individual maximum likelihood gene trees).
I would rather use SpeciesRax or Astral-Pro if you have gene
duplications/losses/transfers.
Best,
Benoit

Le ven. 21 juin 2024 à 06:33, kbsivakumar ***@***.***> a
écrit :

**Comment by karthickbrlab** [comment]
Hi...

How should my astral pro input look..?
((g23405.t1:0.077108,((Sar09g19420R:0.017666,BniB04g36810K:0.048265):0.012736,raps_1708:0.059318):0.013511):0.008844,Sal08g16700L:0.045026,((BraA09g040300.3.5C.1:0.047402,ckale_25704:0.024559):0.030756,((Thlar.0502s0010.1.p:0.107357,(((Carubv10011502m|PACid_20892999:0.046231,Csa03g028770.1:0.081706):0.028572,((Araha.0898s0004.1:0.018376,AL1G38950.t1:0.019819):0.008456,AT1G26760:0.046494):0.016909):0.044529,(AA_scaffold1441_126:0.227215,KFK44587.1:0.071770):0.020218):0.012342):0.008933,c0001_01956g:0.090249):0.067316):0.008921);

((Sar09g18730R:0.035818,BniB04g36310K:0.033197):0.014746,g23459.t1:0.041151,(((BraA09g040940.3.5C.1:0.016108,ckale_25640:0.022337):0.024538,(Sal08g16270L:0.039602,(((AA_scaffold1441_174:0.295595,KFK44476.1:0.084320):0.008148,(Thlar.0015s0412.1.p:0.062236,c0001_01901:0.099463):0.004374):0.014260,((Carubv10009254m|PACid_20888861:0.039444,Csa12024s010.1:0.028995):0.033581,(AL1G37940.t1:0.013010,(AT1G24130:0.029459,Araha.4881s0002.1:0.018362):0.002451):0.017469):0.043071):0.073878):0.008187):0.006586,raps_1661:0.051526):0.011936);

((Araha.2474s0020.1:0.009984,AL5G40290.t1:0.002576):0.002977,AT3G58520:0.022635,(((((c0007_01118:0.042672,(Sal07g14010L:0.005459,((raps_20356:0.019415,(BraA09g050680.3.5C.1:0.007390,ckale_43657:0.005113):0.005325):0.005542,(BniB08g67800K:0.004306,(Sar09g42600R:0.011765,g30815.t1:0.042962):0.004158):0.005375):0.002808):0.030351):0.012479,Thlar.0021s0490.1.p:0.042914):0.017631,KFK35107.1:0.036289):0.010637,(Carubv10019134m|PACid_20886243:0.019061,Csa04g045050.1:0.023924):0.007227):0.002878,AA_scaffold1640_12:0.165524):0.007710);

((KFK33478.1:0.096539,(((Sal10g21190L:0.038728,((Sar05g08580R:0.029276,BniB04g08300K:0.020976):0.015167,((BraA02g037100.3.5C.1:0.039932,(g39005.t1:0.064433,ckale_8960:0.031568):0.010316):0.007761,raps_25021:0.078545):0.005489):0.011588):0.083700,(AA_scaffold2513_18:0.164295,Thlar.0010s0360.1.p:0.054818):0.012928):0.009089,c0003_01534:0.076959):0.010578):0.010423,(Carubv10016843m|PACid_20887967:0.035150,Csa09g005230.1:0.042565):0.024896,(AT2G02980:0.046782,(Araha.70819s0001.1:0.031567,AL5G12600.t1:0.015947):0.016453):0.011365);

these are the four sample gene trees.

how i use astral pro to get species??

with regards
Karthick

**Comment by karthickbrlab** [comment]
Hi.
i have to infer a species tree from a set of gene trees. The previous mail
shows the sample of gene trees I'm having..
thank you
karthick
